#
#Elite Botany Pot Speed & OUtput
#Range: > 1
eliteBotanyPotSpeedOutput = 2
#
#Ultra Botany Pot Speed & Output
#Range: > 1
ultraBotanyPotSpeedOutput = 6
#
#Creative Botany Pot Speed & Output
#Range: > 1
creativeBotanyPotSpeedOutput = 10

